# Generated by Django 4.2.5 on 2024-01-03 16:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
