# Generated by Django 5.0 on 2023-12-28 11:59

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='users',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
