# Generated by Django 5.0 on 2023-12-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0002_alter_lessonpage_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseindexpage',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_status', to='authentication.membershipstatus'),
        ),
    ]
