# Generated by Django 5.0 on 2023-12-29 09:39

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courseindexpage_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='membership_category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_membership', to='course.courseindexpage'),
        ),
        migrations.AlterField(
            model_name='courseindexpage',
            name='membership_type',
            field=models.CharField(choices=[('Worker', 'Worker'), ('New Convert', 'New Convert'), ('Member', 'Member')], default='Member', max_length=100),
        ),
    ]
