# Generated by Django 4.1.8 on 2024-01-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_resource_course_alter_resource_upload_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='upload_resource',
            field=models.URLField(blank=True, help_text='Add the to the location of the file. E.g. Google Drive', null=True),
        ),
    ]
