# Generated by Django 4.2.8 on 2024-05-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='outreach_body',
            new_name='event_body',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='outreach_image',
            new_name='event_image',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='outreach_title',
            new_name='event_title',
        ),
    ]
