# Generated by Django 5.0 on 2023-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Worker', 'Worker'), ('New Convert', 'New Convert'), ('Member', 'Member')], default='Member', max_length=100),
        ),
        migrations.DeleteModel(
            name='MembershipStatus',
        ),
    ]
