# Generated by Django 4.1.8 on 2024-01-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worshipservice',
            name='join_via_facebook_live_link',
        ),
        migrations.RemoveField(
            model_name='worshipservice',
            name='join_via_youtube_live_link',
        ),
        migrations.RemoveField(
            model_name='worshipservice',
            name='join_via_zoom_live_link',
        ),
    ]
