# Generated by Django 4.1.8 on 2024-01-09 23:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0004_homepage_hero_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamNew',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('caption_title', wagtail.fields.RichTextField(blank=True, null=True)),
                ('caption_text', wagtail.fields.RichTextField(blank=True, null=True)),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
