# Generated by Django 4.1.8 on 2024-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_iamnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='cashapp_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='cashapp_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
