# Generated by Django 5.0 on 2023-12-31 15:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_donate_importantpages_sitecontact_sitelogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='caption_title',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
