# Generated by Django 4.1.8 on 2024-01-17 17:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_donate_cashapp_number_donate_cashapp_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamnew',
            name='first_section_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamnew',
            name='first_section_title',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamnew',
            name='second_section_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamnew',
            name='second_section_title',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamnew',
            name='third_section_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iamnew',
            name='third_section_title',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
