# Generated by Django 5.0 on 2024-01-01 20:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactformpage_contactformfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contat_form_fields', to='home.contactformpage'),
        ),
    ]
