# Generated by Django 4.2.8 on 2024-05-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('home', '0007_iamnew_first_section_body_iamnew_first_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
