# Generated by Django 4.2.5 on 2024-01-02 08:22

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactformpage'),
        ),
    ]
