# Generated by Django 4.2.5 on 2024-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_about_general_superintendent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_church_title_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
